packages:
  - apps/*
  - packages/*
  - services/*

catalog:
  vitest: ^3.2.4
  "@vitest/ui": ^3.2.4
  "@vitest/coverage-v8": ^3.2.4
  typescript: ^5.8.3
  tsx: ^4.19.4
  prettier: ^3.5.3
  eslint: ^9.15.0
  "@types/node": ^22.15.21
  dotenv-cli: ^8.0.0
  winston: ^3.17.0
  "@paralleldrive/cuid2": ^2.2.2
  "@ai-sdk/openai": ^1.3.24
  "@mastra/evals": ^0.14.4
  "zod": ^3.25.74
  drizzle-orm: ^0.44.4
  tsup: ^8.5.0
  pg: ^8.16.0
  "@types/pg": 8.16.0
  "@faker-js/faker": ^9.9.0
  "drizzle-kit": ^0.31.8
  "@mastra/core": ^0.24.9
  "@mastra/loggers": ^0.10.19
  "mastra": ^0.18.9
  "typescript-eslint": ^8.37.0
  "@eslint/js": ^9.31.0
  "@typescript-eslint/eslint-plugin": ^8.35.1
  "@typescript-eslint/parser": ^8.35.1
  "@vercel/style-guide": ^6.0.0
  "eslint-config-next": ^15.3.2
  "eslint-config-prettier": ^10.1.5
  "eslint-plugin-only-warn": ^1.1.0
  "eslint-plugin-react": ^7.37.5
  "eslint-plugin-react-hooks": ^5.2.0
  "eslint-plugin-unused-imports": ^4.1.4
  "prettier-package-json": ^2.8.0
  "prettier-plugin-organize-imports": ^4.1.0
  "npm-run-all": ^4.1.5
  "tailwind-merge": ^3.4.0
  "tw-animate-css": ^1.4.0
  "del-cli": ^6.0.0
