packages:
  - apps/*
  - packages/*
  - services/*

catalog:
  vitest: ^3.2.4
  "@vitest/ui": ^3.2.4
  "@vitest/coverage-v8": ^3.2.4
  typescript: ^5.8.3
  tsx: ^4.19.4
  prettier: ^3.5.3
  eslint: ^9.15.0
  "@types/node": ^22.15.21
  dotenv-cli: ^8.0.0
  dotenv: ^16.4.7
  winston: ^3.17.0
  "@t3-oss/env-core": ^0.13.4
  "@paralleldrive/cuid2": ^2.2.2
  "@ai-sdk/openai": ^1.3.24
  "@mastra/evals": ^0.14.4
  "zod": ^3.25.74
  tailwindcss: ^4
  "@tailwindcss/postcss": ^4
  drizzle-orm: ^0.44.4
  fastify: ^5.4.0
  better-auth: ^1.3.5
  sst: ^3.17.10
  tsup: ^8.5.0
  pg: ^8.16.0
  "@ts-rest/core": ^3.52.1
  limax: ^4.1.0
  "@mastra/core": ^0.24.9
  "@mastra/libsql": ^0.16.4
  "@mastra/loggers": ^0.10.19
  "@mastra/memory": ^0.15.13
  "@mastra/pg": ^0.17.10
  "@mastra/fastembed": ^0.10.7
  "@mastra/node-audio": ^0.1.7
  "@mastra/voice-deepgram": ^0.11.13
  "@mastra/voice-elevenlabs": ^0.11.12
  "@mastra/voice-google": ^0.11.12
  "@mastra/voice-google-gemini-live": ^0.11.1
  "@mastra/voice-openai": ^0.11.12
  "@mastra/voice-openai-realtime": ^0.11.12
  "mastra": ^0.18.9
  "typescript-eslint": ^8.37.0
  "@eslint/js": ^9.31.0
  "@typescript-eslint/eslint-plugin": ^8.35.1
  "@typescript-eslint/parser": ^8.35.1
  "@vercel/style-guide": ^6.0.0
  "eslint-config-next": ^15.3.2
  "eslint-config-prettier": ^10.1.5
  "eslint-plugin-only-warn": ^1.1.0
  "eslint-plugin-react": ^7.37.5
  "eslint-plugin-react-hooks": ^5.2.0
  "eslint-plugin-unused-imports": ^4.1.4
  "prettier-package-json": ^2.8.0
  "prettier-plugin-organize-imports": ^4.1.0
  "npm-run-all": ^4.1.5
  "react": 19.0.0
  "react-dom": 19.0.0
  "@types/react": 19.1.12
  "@types/react-dom": 19.1.9
  "@fastify/aws-lambda": ^5.1.4
  "@aws-sdk/client-sesv2": ^3.922.0
  "@aws-sdk/client-sns": ^3.922.0
  "@aws-sdk/client-sqs": ^3.922.0
  "@aws-sdk/s3-request-presigner": ^3.922.0
  "@aws-sdk/client-s3": ^3.922.0
  "date-fns": ^4.1.0
  "date-fns-tz": ^3.2.0
  "@types/pg": 8.16.0
  "@faker-js/faker": ^9.9.0
  "drizzle-kit": ^0.31.8
  "ioredis": ^5.8.2
  "@types/ioredis": ^5.0.0
  "aws-cdk-lib": ^2.233.0
  "tailwind-merge": ^3.4.0
  "tw-animate-css": ^1.4.0
  "@fastify/compress": ^8.3.1
  "@fastify/cors": ^11.2.0
  "@fastify/helmet": ^12.0.1
  "@fastify/rate-limit": ^10.3.0
  "@slack/oauth": ^3.0.4
  "@slack/web-api": ^7.13.0
  "@ts-rest/fastify": ^3.52.1
  "fastify-plugin": ^5.1.0
  "jose": ^6.1.3
  "undici": ^7.16.0
  "vitest-mock-extended": ^3.1.0
  "expo-server-sdk": ^4.0.0
  "axios": ^1.13.2
  "form-data": ^4.0.5
  "@types/form-data": ^2.5.2
  "del-cli": ^6.0.0
